{{- if and (eq .Values.ingressRoute.scheme "https") .Values.ingressRoute.insecureSkipVerify }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ include "helm-chart.fullname" . }}-insecure
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  insecureSkipVerify: true
{{- end }}
